### ISSUE TITLE
[Feature] CI를 위한 테스트코드 선행 작업

### ISSUE THREAD

**Issue by kimboha** [3-advisor/seohyeonee#21]
- [x] CI 를 위해 간단한 테스트 코드 추가하기
- [x] jest에 mongodb 설정 또는 그냥 mocha 쓰기
  > front 쪽은 jest 쓸 예정

**Comment by kimboha** [comment]
@mgcation 
jest로 테스트할때 이런 경고가 뜨네요,

`Mongoose: looks like you're trying to test a Mongoose app with Jest's default jsdom test environment. Please make sure you read Mongoose's docs on configuring Jest to test Node.js apps: http://mongoosejs.com/docs/jest.html`

**Comment by mgcation** [comment]
반영할게요!

**Comment by mgcation** [comment]
굳굳!
반영할게요~
