### ISSUE TITLE
[검토내용] 브랜치 관리

### ISSUE THREAD

**Issue by arori** [3-advisor/seohyeonee#23]
## 관련 PR, ISSUE
#3 #18

## 이슈내용
마스터 브랜치에 바로 머지하지말고(위 이슈처럼 에러발생 가능성), 
Feature를 Develop브랜치에 머지하고 
Master에는 현재 리얼(라인 봇)에 나가있는 내용만 관리할 수 있음 좋겠습니다.

**Comment by mgcation** [comment]
좋은 의견입니다.
#18 같은 경우 feature 보다 bugfix 또는 hotfix 등으로 관리하면 더 좋을 것 같아요

**Comment by arori** [comment]
develop 브랜치 생성했습니다.
