### ISSUE TITLE
DB 구조 설계 및 구현

### ISSUE THREAD

**Issue by kimboha** [3-advisor/seohyeonee#8]
- 장소
- 태그
- 설명&팁 (추가정보)

를 담는 DB구조 설계

**Comment by kimboha** [comment]
> 음식점
- 아이디 `Int`
- 이름 `String`
- 설명 `String`
- 태그 값 `Array<id>`

> 태그
- 아이디 `Int`
- 태그 값 `String`
- 해당 음식점 리스트 `Array<id>`

--------------------

> 고려 요소
- Date (작성, 수정)

**Comment by mgcation** [comment]
# sql 
[sql의 경우](http://howto.philippkeller.com/2005/04/24/Tags-Database-schemas/)
테이블을 3개 두고

> 음식점 / 태그 / 음식점-태그 

로 활용하는게 가장 잘 정규화된 방법이라고 하는데

# nosql
[nosql은](https://www.techighness.com/post/nosql-many-to-many-bound-unbound-associative-examples/)
mongodb의 document의 최대 사이즈가 16MB 이기 때문에
이 보다 커질 우려가 있는 구조(unbound)의 경우
위 처럼 3개의 테이블 방법을 사용하고
그렇지 않다면 2개로 나눠서 사용해도 괜찮다고 합니다
우리가 사용하는 음식점 태그의 경우 스케일이 어마어마하게 크진 않을 듯 한데.. 의견을 나눠봐야 할 것 같아요

---

그리고 그래프 디비라는게 있던데 혹시 아시는 분 계신가요
https://neo4j.com/

**Comment by kimboha** [comment]
https://github.com/3-advisor/seohyeonee/blob/c33c2be731273255d77412425b60f46bd00c8e1e/dev_db/readme.md
